/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi2023.mathproject;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kseny
 */
public class VisualFrame extends javax.swing.JFrame {
    DataReader dr;
    DataStorage ds;
    
    public VisualFrame() {
        initComponents();
        dr = new DataReader();
        ds = new DataStorage();
        numbVariantTextField.setText("7");
        
        DefaultTableModel model = DataManipulation.drawModel(new ArrayList<>(), new ArrayList<>(), 
                                                             ds.getNamesParameters(), 0);
        DefaultTableModel model2 = DataManipulation.drawModel(new ArrayList<>(), new ArrayList<>(), 
                                                             ds.getNamesParameters2(), 
                                                             ds.getNamesParameters().length);
        parametersTable.setModel(model);
        corTable.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        parametersTable = new javax.swing.JTable();
        countParamButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        loadDataButton = new javax.swing.JButton();
        numbVariantTextField = new javax.swing.JTextField();
        numbVariantLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        corTableScrollPane = new javax.swing.JScrollPane();
        corTable = new javax.swing.JTable();
        exportDataButton = new javax.swing.JButton();
        messageExpLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        exceptionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startPanel.setBackground(new java.awt.Color(204, 204, 204));

        parametersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parameters"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(parametersTable);

        countParamButton.setText("Рассчитать параметры");
        countParamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countParamButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nameLabel.setText("Parameters for variant");
        nameLabel.setEnabled(false);

        loadDataButton.setText("Загрузить данные варианта");
        loadDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataButtonActionPerformed(evt);
            }
        });

        numbVariantTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numbVariantLabel.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        numbVariantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numbVariantLabel.setText("номер варианта");
        numbVariantLabel.setFocusable(false);
        numbVariantLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        messageLabel.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setFocusable(false);
        messageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        corTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parameters"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        corTableScrollPane.setViewportView(corTable);

        exportDataButton.setText("Выгрузить данные варианта");
        exportDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportDataButtonActionPerformed(evt);
            }
        });

        messageExpLabel.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        messageExpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageExpLabel.setFocusable(false);
        messageExpLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        closeButton.setText("CLOSE");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        exceptionLabel.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exceptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countParamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableScrollPane)
                    .addComponent(corTableScrollPane)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numbVariantLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(messageExpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addComponent(loadDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numbVariantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exportDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(countParamButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadDataButton)
                    .addComponent(numbVariantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportDataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numbVariantLabel)
                    .addComponent(messageExpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exceptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataButtonActionPerformed
        try {
            ds.clearData();
            int numbVariant = Integer.parseInt(numbVariantTextField.getText());
            dr.ReadXLSX(ds, ".\\ДЗ4.xlsx", numbVariant);
            messageLabel.setText("удалось прочитать файл (вариант " + numbVariant + ")");            
        } catch (IOException | NumberFormatException ex) {
            messageLabel.setText("не удалось прочитать файл ");
            exceptionLabel.setText(ex.getMessage());
        }
        
    }//GEN-LAST:event_loadDataButtonActionPerformed

    private void countParamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countParamButtonActionPerformed
        ArrayList<ArrayList<Object>> parameters = DataManipulation.countParams(ds.getSamples());
        ds.setResults(parameters);
        DefaultTableModel model = DataManipulation.drawModel(parameters, ds.getNames(), 
                ds.getNamesParameters(), 0);
        DefaultTableModel model2 = DataManipulation.drawModel(parameters,  ds.getNames2(), 
                ds.getNamesParameters2(), ds.getNamesParameters().length);
        
        parametersTable.setModel(model);
        corTable.setModel(model2);
    }//GEN-LAST:event_countParamButtonActionPerformed

    private void exportDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportDataButtonActionPerformed
        String fileName = ".\\Результаты.xlsx";
        try {
            dr.ExportXLSX(ds, fileName);
            messageExpLabel.setText("удалось загрузить данные в файл");     
        } catch (IOException ex) {
            messageExpLabel.setText("не удалось загрузить данные в файл");
            exceptionLabel.setText("Ошибка: " + ex.getMessage());
        }


    }//GEN-LAST:event_exportDataButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
  
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTable corTable;
    private javax.swing.JScrollPane corTableScrollPane;
    private javax.swing.JButton countParamButton;
    private javax.swing.JLabel exceptionLabel;
    private javax.swing.JButton exportDataButton;
    private javax.swing.JButton loadDataButton;
    private javax.swing.JLabel messageExpLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numbVariantLabel;
    private javax.swing.JTextField numbVariantTextField;
    private javax.swing.JTable parametersTable;
    private javax.swing.JPanel startPanel;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
